export const mainNavItems = [
  { title: 'Home', href: '' },
  { title: 'Mac', href: 'Mac' },
  { title: 'iPad', href: 'iPad' },
  { title: 'iPhone', href: 'iPhone' },
  { title: 'Watch', href: 'Watch' },
  { title: 'TV', href: 'TV' },
  { title: 'Music', href: 'Music' },
  { title: 'Support', href: 'Support' },
];

export const subNavItems = {
  mac: [
    { title: 'MacBook Air' },
    { title: 'MacBook Pro' },
    { title: 'iMac' },
    { title: 'iMac Pro' },
    { title: 'Mac Pro' },
    { title: 'Mac mini' },
    { title: 'Compare' },
    { title: 'Pro Display XDR' },
    { title: 'Accessories' },
    { title: 'Catalina' },
  ],
  iPad: [
    { title: 'iPad Air' },
    { title: 'iPad Pro' },
    { title: 'iPad' },
    { title: 'iPad mini' },
    { title: 'Compare' },
    { title: 'Apple Pencil' },
    { title: 'Smart Keyboard' },
    { title: 'Accessories' },
    { title: 'iPadOS' },
  ],
  iPhone: [
    { title: 'iPhone 11 Pro' },
    { title: 'iPhone 11' },
    { title: 'iPhone Xr' },
    { title: 'iPhone 8' },
    { title: 'Compare' },
    { title: 'Apple Card' },
    { title: 'Airpods' },
    { title: 'Accessories' },
    { title: 'iOS13' },
  ],
  watch: [
    { title: 'Apple Watch Series 5' },
    { title: 'Apple Watch Nike' },
    { title: 'Apple Watch Hermes' },
    { title: 'Apple Watch Edition' },
    { title: 'Apple Watch Series 3' },
    { title: 'Compare' },
    { title: 'Bands' },
    { title: 'Airpods' },
    { title: 'Accessories' },
    { title: 'watchOS' },
  ],
  tv: [
    { title: 'Apple TV App' },
    { title: 'Apple TV+' },
    { title: 'Apple TV 4K' },
    { title: 'Apple TV HD' },
    { title: 'Airplay' },
    { title: 'Accessories' },
  ],
  music: [
    { title: 'Apple Music' },
    { title: 'Homepod' },
    { title: 'Airpods' },
    { title: 'iPod touch' },
    { title: 'Music Accessories' },
    { title: 'Gift Cards' },
  ],
};
