export const mainNavItems = [
  { id: 0, title: 'Home', url: '' },
  { id: 1, title: 'Mac', url: 'Mac' },
  { id: 2, title: 'iPad', url: 'iPad' },
  { id: 3, title: 'iPhone', url: 'iPhone' },
  { id: 4, title: 'Watch', url: 'Watch' },
  { id: 5, title: 'TV', url: 'TV' },
  { id: 6, title: 'Music', url: 'Music' },
  { id: 7, title: 'Support', url: 'Support' },
];

export const subNavItems = [
  {
    id: 1,
    url: 'Mac',
    Mac: [
      { title: 'MacBook Air' },
      { title: 'MacBook Pro' },
      { title: 'iMac' },
      { title: 'iMac Pro' },
      { title: 'Mac Pro' },
      { title: 'Mac mini' },
      { title: 'Compare' },
      { title: 'Pro Display XDR' },
      { title: 'Accessories' },
      { title: 'Catalina' },
    ],
  },
  {
    id: 2,
    url: 'iPad',
    iPad: [
      { title: 'iPad Air' },
      { title: 'iPad Pro' },
      { title: 'iPad' },
      { title: 'iPad mini' },
      { title: 'Compare' },
      { title: 'Apple Pencil' },
      { title: 'Smart Keyboard' },
      { title: 'Accessories' },
      { title: 'iPadOS' },
    ],
  },
  {
    id: 3,
    url: 'iPhone',
    iPhone: [
      { title: 'iPhone 11 Pro' },
      { title: 'iPhone 11' },
      { title: 'iPhone Xr' },
      { title: 'iPhone 8' },
      { title: 'Compare' },
      { title: 'Apple Card' },
      { title: 'Airpods' },
      { title: 'Accessories' },
      { title: 'iOS13' },
    ],
  },
  {
    id: 4,
    url: 'Watch',
    Watch: [
      { title: 'Apple Watch Series 5' },
      { title: 'Apple Watch Nike' },
      { title: 'Apple Watch Hermes' },
      { title: 'Apple Watch Edition' },
      { title: 'Apple Watch Series 3' },
      { title: 'Compare' },
      { title: 'Bands' },
      { title: 'Airpods' },
      { title: 'Accessories' },
      { title: 'watchOS' },
    ],
  },
  {
    id: 5,
    url: 'TV',
    TV: [
      { title: 'Apple TV App' },
      { title: 'Apple TV+' },
      { title: 'Apple TV 4K' },
      { title: 'Apple TV HD' },
      { title: 'Airplay' },
      { title: 'Accessories' },
    ],
  },
  {
    id: 6,
    url: 'Music',
    Music: [
      { title: 'Apple Music' },
      { title: 'Homepod' },
      { title: 'Airpods' },
      { title: 'iPod touch' },
      { title: 'Music Accessories' },
      { title: 'Gift Cards' },
    ],
  },
];
